AWSTemplateFormatVersion: "2010-09-09"
Description: Use this Magic CFN template to create your environment!
Parameters:
   DeviceName :
     Type: AWS::IoT::Thing 
     Description : enter the IoT device name
   FunctionName : 
      Type: AWS::Lambda::Function 
      Description : enter the Function name
    S3BucketName : 
      Type: AWS::S3::Bucket 
      Description : enter the Function name
Description: Use this Magic wand to create your environment (may incur cost)
Resources:
  Type: AWS::IoT::Thing
  Properties: 
    AttributePayload: 
      Images JPG
    ThingName: !Ref DeviceName
  Type: AWS::Lambda::Function
  Properties:
    
      


