AWSTemplateFormatVersion: "2010-09-09"
Description: Use this Magic wand to create your environment (may incur cost)
Resources:
  Type: AWS::IoT::Thing
  Properties: 
    AttributePayload: 
      AttributePayload
    ThingName: String
