AWSTemplateFormatVersion: "2010-09-09"
Description: # Use this Magic CFN template to create your environment!
Parameters:
   DeviceNameIoT :
     Type: AWS::IoT::Thing 
     Description : # enter the IoT device name
   FunctionNameLambda : 
      Type: AWS::Lambda::Function 
      Description : # enter the Function name
   S3BucketNameIoT : 
      Type: AWS::S3::Bucket 
      Description : # enter the Bucket name Note: must be Unique
Resources:
   S3BucketName: !Ref S3BucketNameIoT
    
   LambdaBasicExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CustomLambdaS3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - S3:PutObject
                  - S3:GetObject
                Resource: !GetAtt 
    DeviceName: !Ref DeviceNameIoT
    Properties: 
      AttributePayload: 
        Images JPG
    FunctionName: !Ref FunctionNameLambda 
    Properties:
     - Runtime: python 3.9 # Or use a 3.x version that you wish
     - Timeout: 30 
      


